### ISSUE TITLE
buttons to control break timer

### ISSUE THREAD

**Issue by hunkjazz** [roldanjrCodeArts9711/productivity-timer#101]
**Is your feature request related to a problem? Please describe.**
Once in a while I need to skip, pause or restart breaks. The app don't have this feature.

**Describe the solution you'd like**
Just control buttons for breaks, like work timer have.

**Comment by roldanjrCodeArts9711** [comment]
I'm sorry but it has. 
Just don't enable `Strict Mode` feature, it will blocks you from using those buttons when timer started.

**Comment by hunkjazz** [comment]
Thanks and sorry.
