### ISSUE TITLE
break timer shouldn't hide tabs

### ISSUE THREAD

**Issue by hunkjazz** [roldanjrCodeArts9711/productivity-timer#102]
**Is your feature request related to a problem? Please describe.**

I like to tweak configs and check how many tasks are left. It may happen during break time, even though it sounds stupid, the app shouldn't control when I can do these things.

**Comment by roldanjrCodeArts9711** [comment]
What do you mean by that. Can you elaborate it?

**Comment by hunkjazz** [comment]
I was not aware of fullscreen break timer.
