### ISSUE TITLE
thank you for the great app!

### ISSUE THREAD

**Issue by hunkjazz** [roldanjrCodeArts9711/productivity-timer#104]
It's the best pomodoro app I've found so far.

1. Beautiful UI;
2. Good UX;
3. Good features.

I really like it!

Because of that I have created these many issues.
I just want it to enhance.
I hope you don't get upset.

**Comment by roldanjrCodeArts9711** [comment]
Thank you for the issues. It's my pleasure. 

Surely it will improve the app. I'm sorry if I can't develop some of them right now.
