### ISSUE TITLE
Installed with snap on ubuntu 19.04, can't run it

### ISSUE THREAD

**Issue by lourenzo** [roldanjrCodeArts9711/productivity-timer#43]
Hello, I've installed `productivity-timer` from snap, on ubuntu 19.04, and there's no desktop entry or binary with the `productivity-timer`name, how can I run the program?

Thanks in advance!

Lourenzo Ferreira

**Comment by feferna** [comment]
I can confirm... I installed from snapcraft.io, but I cannot run the app. Is there any instructions in how to compile the app from the sources?

**Comment by roldanjrCodeArts9711** [comment]
I'm so sorry for that. It's not tested yet on real Linux machine. I am very busy last month, maybe this month hopefully or next month I will fixed that. Thank you very much for your concerns. :)

**Comment by roldanjrCodeArts9711** [comment]
> Hello, I've installed `productivity-timer` from snap, on ubuntu 19.04, and there's no desktop entry or binary with the `productivity-timer`name, how can I run the program?
> 
> Thanks in advance!
> 
> Lourenzo Ferreira

I'm so sorry for that. It's not tested yet on real Linux machine. I am very busy last months, maybe this month hopefully or next month I will fixed that. Thank you very much for your concerns. :)

**Comment by roldanjrCodeArts9711** [comment]
> I can confirm... I installed from snapcraft.io, but I cannot run the app. Is there any instructions in how to compile the app from the sources?

I am so sorry for that. I will try to fix it maybe this month or next month. Thank you 👍

**Comment by roldanjrCodeArts9711** [comment]
@lourenzo & @feferna, you can now installed it from snapcraft.io and it will work properly. It works on my Manjaro and hopefully works for you too.

**Comment by feferna** [comment]
Yep, it is working fine now on Kubuntu 19.10! :+1: 

Thank you very much!

**Comment by roldanjrCodeArts9711** [comment]
> Yep, it is working fine now on Kubuntu 19.10! 
> 
> Thank you very much!

@feferna I'm glad it works for you now. 
Also, please raised an issue if there is no "Text To Speech" sound notification on your machine so that I will know. Thank you!
