### ISSUE TITLE
When timer is running, the window always on top

### ISSUE THREAD

**Issue by fsevenm** [roldanjrCodeArts9711/productivity-timer#45]
I successfully built the source on my Ubuntu 18.04.x with deb package target. I installed it and run it. But when the timer is running, I can't even put the app window behind my other apps. When I hide it by clicking the X red button, sometimes it hides but mostly it hides in second (or maybe some milliseconds) then it appears again at the very front. It is kinda like a bug. Any suggestions?

**Comment by roldanjrCodeArts9711** [comment]
> I successfully built the source on my Ubuntu 18.04.x with deb package target. I installed it and run it. But when the timer is running, I can't even put the app window behind my other apps. When I hide it by clicking the X red button, sometimes it hides but mostly it hides in second (or maybe some milliseconds) then it appears again at the very front. It is kinda like a bug. Any suggestions?

Sorry about that. May I know if you enabled "Fullscreen On Break" or not so that I can answer your question. Thank you 😊

**Comment by roldanjrCodeArts9711** [comment]
@fsevenm you can now try to install the snap version of it. It works on my Manjaro. Hopefully it works for you.

**Comment by fsevenm** [comment]
> > I successfully built the source on my Ubuntu 18.04.x with deb package target. I installed it and run it. But when the timer is running, I can't even put the app window behind my other apps. When I hide it by clicking the X red button, sometimes it hides but mostly it hides in second (or maybe some milliseconds) then it appears again at the very front. It is kinda like a bug. Any suggestions?
> 
> Sorry about that. May I know if you enabled "Fullscreen On Break" or not so that I can answer your question. Thank you

Sorry for the very late response, I am really busy. I had tested it, but it still the same in both conditions. Here is a video, I recorded it, so you can see it clearly. https://filebin.net/h706qxnheaa68kqv/productivity_timer.mp4?t=57oka96q. This video will only valid in a week.

**Comment by fsevenm** [comment]
> @fsevenm you can now try to install the snap version of it. It works well on my Manjaro. Hopefully it works for you too.
> ![image](https://user-images.githubusercontent.com/38913069/73656270-c0c9a500-46ca-11ea-92be-a6a57a90d97c.png)

Great to see it works on your Manjaro, it still doesn't work on my Ubuntu 18.04 though. I attach my terminal logs while I was trying to open this app using 4 types of commands.
![158073873](https://user-images.githubusercontent.com/29963765/73659505-5cf6aa80-46d1-11ea-8c1c-399f43c0b260.png)
![image](https://user-images.githubusercontent.com/29963765/73659683-b959ca00-46d1-11ea-9b8e-af35558602a8.png)

**Comment by roldanjrCodeArts9711** [comment]
> trying to open this app using 4 types o

@fsevenm It works fine when you run it not on the terminal. But if you want to run the app inside the terminal  just put `--no-sandbox` flag.

**Comment by roldanjrCodeArts9711** [comment]
> > > I successfully built the source on my Ubuntu 18.04.x with deb package target. I installed it and run it. But when the timer is running, I can't even put the app window behind my other apps. When I hide it by clicking the X red button, sometimes it hides but mostly it hides in second (or maybe some milliseconds) then it appears again at the very front. It is kinda like a bug. Any suggestions?
> > 
> > 
> > Sorry about that. May I know if you enabled "Fullscreen On Break" or not so that I can answer your question. Thank you
> 
> Sorry for the very late response, I am really busy. I had tested it, but it still the same in both conditions. Here is a video, I recorded it, so you can see it clearly. https://filebin.net/h706qxnheaa68kqv/productivity_timer.mp4?t=57oka96q. This video will only valid in a week.

I see your problem. It doesn't behave like that on my machine. Maybe try the snap version on it and we'll discuss its behavior and try to fixed it if still persist.

**Comment by fsevenm** [comment]
Actually I have 2 versions of the app installed on my machine, first one I installed with snap which won't open both in terminal (with `--no-sandbox`) and direct app icon click. And the second one that I built myself which can open but behave weirdly as you can see in a video I shared with you above.

**Comment by roldanjrCodeArts9711** [comment]
> Actually I have 2 versions of the app installed on my machine, first one I installed with snap which won't open both in terminal (with `--no-sandbox`) and direct app icon click. And the second one that I built myself which can open but behave weirdly as you can see in a video I shared with you above.

@fsevenm I don't actually really know what is the cause of that but I think you might need to uninstall the first one that isn't a snap package.

**Comment by roldanjrCodeArts9711** [comment]
Here's the screenshot when I ran the app inside the terminal with `--no-sandbox` flag.

![image](https://user-images.githubusercontent.com/38913069/73665521-34c07900-46dc-11ea-8152-df9566735893.png)

**Comment by fsevenm** [comment]
Hmm, I successfully run the snap version of this app. I am on Wayland session actually, and apparently, there is a bug after logged in to Wayland then try to switch to X11 session as mentioned [here](https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1749484). But the issue as the question still occurs.

**Comment by roldanjrCodeArts9711** [comment]
> Hmm, I successfully run the snap version of this app. I am on Wayland session actually, and apparently, there is a bug after logged in to Wayland then try to switch to X11 session as mentioned [here](https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1749484). But the issue as the question still occurs.

Maybe I need to disable WAYLAND for that. I try to figure and fix that out tommorow. Thanks by the way. :)

**Comment by fsevenm** [comment]
You are welcome.

**Comment by roldanjrCodeArts9711** [comment]
> You are welcome.

You can now try the latest build of the package. Please let me know if it solved the problem. Thank you.

**Comment by fsevenm** [comment]
The app now runs on my machine but its behavior is still the same. This can be an issue on Ubuntu with Gnome desktop I thought. More research is still needed here, I also do research about this issue. I'll share if I find something new.

**Comment by roldanjrCodeArts9711** [comment]
> The app now runs on my machine but its behavior is still the same. This can be an issue on Ubuntu with Gnome desktop I thought. More research is still needed here, I also do research about this issue. I'll share if I find something new.

Thanks for your help @fsevenm. If I will have time, I will try to install Ubuntu on Virtualbox to figure out what wrong and have a better picture of the problem.

**Comment by roldanjrCodeArts9711** [comment]
Hey @fsevenm ? Is this issue still persist?
