### ISSUE TITLE
The app blocks Ctrl-R hotkey

### ISSUE THREAD

**Issue by sabian** [roldanjrCodeArts9711/productivity-timer#49]
When app is running Ctrl-R hotkey doesn't work system-wide. Browsers, terminal, etc.
Linux Mint 19.3 Cinnamon

**Comment by roldanjrCodeArts9711** [comment]
> When app is running Ctrl-R hotkey doesn't work system-wide. Browsers, terminal, etc.
> Linux Mint 19.3 Cinnamon

@sabian Ctrl+R hotkey is for app reload which is being disabled on production.
Can you give some use cases why you need that hotkey? Thank you.

**Comment by sabian** [comment]
Browsers - page reload
Terminal - reverse search through history
Text editors and IDE - text replace

**Comment by roldanjrCodeArts9711** [comment]
> Browsers - page reload
> Terminal - reverse search through history
> Text editors and IDE - text replace

@sabian I get it. But I disabled it on production due to the fact that if I enabled it, the users of the app including me can easily break the Pomodoro rules which is not what I want.

**Comment by jedsonmelo** [comment]
@roldanjrCodeArts9711  couldn't you disable only on app?

**Comment by roldanjrCodeArts9711** [comment]
> @roldanjrCodeArts9711 couldn't you disable only on app?

I'm sorry for that @jedsonmelo .
I'm currently working for the new version of the app and all issues here I will try to solve. 
If you like the app, use it of just install it for the mean time in order for you to be updated when I release the new version of it. 


![image](https://user-images.githubusercontent.com/38913069/78675214-4eb64c00-7917-11ea-8556-e2ad029b76f9.png)

**Comment by sekwah41** [comment]
That new version looks pretty amazing. Though for now you could just swap the dev usable hotkeys/blocked hotkey combos to enable and disable on blur and unblur.

```
  let blockShortcuts = [
    {
      key: "CommandOrControl+R",
      callback: () => isDev && win.reload()
    },
    {
      key: "CommandOrControl+Shift+R",
      callback: () => isDev && win.reload()
    },
    {
      key: "CommandOrControl+Alt+Q",
      callback: () => isDev && app.quit()
    }
  ];

  win.on("focus", () =>
      blockShortcuts.map(({ key, callback }) =>
          globalShortcut.register(key, callback)
      ));
  win.on("blur", () =>
      blockShortcuts.map(({ key, }) =>
          globalShortcut.unregister(key)
      ));
```
I can make a pr with the basic changes as I have tested them so far and there seem to be no issues though they are pretty small changes but make the little application useable for devs who may need those keybinds and don't seem to introduce the issues you brought up unless I am missing a major oversight.

**Comment by roldanjrCodeArts9711** [comment]
> That new version looks pretty amazing. Though for now you could just swap the dev usable hotkeys/blocked hotkey combos to enable and disable on blur and unblur.
> 
> ```
>   let blockShortcuts = [
>     {
>       key: "CommandOrControl+R",
>       callback: () => isDev && win.reload()
>     },
>     {
>       key: "CommandOrControl+Shift+R",
>       callback: () => isDev && win.reload()
>     },
>     {
>       key: "CommandOrControl+Alt+Q",
>       callback: () => isDev && app.quit()
>     }
>   ];
> 
>   win.on("focus", () =>
>       blockShortcuts.map(({ key, callback }) =>
>           globalShortcut.register(key, callback)
>       ));
>   win.on("blur", () =>
>       blockShortcuts.map(({ key }) =>
>           globalShortcut.unregister(key)
>       ));
> ```
> 
> I can make a pr with the basic changes as I have tested them so far and there seem to be no issues though they are pretty small changes but make the little application useable for devs who may need those keybinds and don't seem to introduce the issues you brought up unless I am missing a major oversight.

Yes please, since I'm very busy right now. Thank you for that. @sekwah41 👍
