### ISSUE TITLE
Wonderful app but certain documentation is lacking

### ISSUE THREAD

**Issue by Quest1mc** [roldanjrCodeArts9711/productivity-timer#59]
Ok 1st thing 1st I like the app the UI is nice and easy to work with 
.However my challenge is that it locks up the key board and disables parts of the mouse functionality once it decided you are on a break ...and this is nowhere in the documentation for this app. 

If you don't mind getting in contact I'd like to help with the documentation of the features as this lock came as a welcome/unwelcome surprise. I'm sure others have come across this and simply thought the app is not functioning as designed but I would like to see a toggle for disabling this feature as well as documentation covering it. 
 GREAT WORK!

**Comment by roldanjrCodeArts9711** [comment]
@Quest1mc I'm so sorry about that. Any possible help are very much welcome.

I am so busy right now. I really want to improve every aspect of the app including the documentation and actually planning to build a web page specifically for the documentation but I still have a lot of work to do right now so I can't do it as of this moment. 

Lately I'm working on the updates and new features of the app but due to my priorities right now it was being stopped for the mean time. 

![image](https://user-images.githubusercontent.com/38913069/77665619-df596780-6fba-11ea-9430-a972dfc9eca6.png)
![image](https://user-images.githubusercontent.com/38913069/77665648-eaac9300-6fba-11ea-902d-76ce3ceae360.png)
![image](https://user-images.githubusercontent.com/38913069/77665703-fac47280-6fba-11ea-84b7-fc9045c16b07.png)
![image](https://user-images.githubusercontent.com/38913069/77665722-031cad80-6fbb-11ea-9ae4-8705808b5694.png)

If you want to help. I will be very happy too. 👍

**Comment by Quest1mc** [comment]
ok no problem i'd be happy to help you with some documentation as my coding is still not so great yet.
Questions when you are on a break it locks down your computer key board and mouse is this a feature confirm .... if so please add me to the repo so that I can mention it in the readme. also a nice feature would be to be able to turn this off. Sometimes you take a break from the project but you want to do personal stuff i.e look at kittens to relax :) and this will allow users to decide for themselves if they want total lockdown or not

**Comment by Quest1mc** [comment]
or is that strict mode ? if it is in the app I suggest an info box to give users this knowledge

**Comment by roldanjrCodeArts9711** [comment]
> ok no problem i'd be happy to help you with some documentation as my coding is still not so great yet.
> Questions when you are on a break it locks down your computer key board and mouse is this a feature confirm .... if so please add me to the repo so that I can mention it in the readme. also a nice feature would be to be able to turn this off. Sometimes you take a break from the project but you want to do personal stuff i.e look at kittens to relax :) and this will allow users to decide for themselves if they want total lockdown or not

Actually you can disabled `Fullscreen On Break` if you don't want to have a break that makes your computer blocks you from any activity. 
![image](https://user-images.githubusercontent.com/38913069/77741072-3dd02580-704f-11ea-84fa-11f58f2ae293.png)

Also if you have read my documentation, I mentioned it there
![image](https://user-images.githubusercontent.com/38913069/77740777-c8fceb80-704e-11ea-9828-3b30488df4de.png)

Anyway, you can freely edit the `README.md` and pull some request if you want. 👍

**Comment by roldanjrCodeArts9711** [comment]
> is that strict mode ? if it is in the app I suggest an info box to give users this knowled

`Strict Mode` is only in version 2. Hopefully sooner or later I can continue the version 2 of it.

**Comment by Quest1mc** [comment]
add this line to the readme

> ### features
>  when enabled FULL SCREEN ON BREAK this feature disables your keyboard and mouse for the duration of break.

**Comment by roldanjrCodeArts9711** [comment]
> add this line to the readme
> 
> > ### features
> > when enabled FULL SCREEN ON BREAK this feature disables your keyboard and mouse for the duration of break.

Yes sure. 👍 

![image](https://user-images.githubusercontent.com/38913069/77776278-b43d4980-7088-11ea-9c4d-179914d14a22.png)

Soon I will improve everything including the documentations. Thank you for your concerns and help.

**Comment by aahilkabir** [comment]
How one can download and run the code?

Pls give details about frame work used and how to run the entire code after downloading!

**Comment by sekwah41** [comment]
Are these designs the concept designs to be made or is that the current state of a private branch you have? If you are still working on it by the time I am done with uni in a few weeks I can lend a hand testing on different Linux distributions.

**Comment by roldanjrCodeArts9711** [comment]
> How one can download and run the code?
> 
> Pls give details about frame work used and how to run the entire code after downloading!

I'm really sorry about not adding that @aahilkabir due that I'm new to open source and I didn't think before about collaborating with other developers but now I probably do that.

**Comment by roldanjrCodeArts9711** [comment]
> Are these designs the concept designs to be made or is that the current state of a private branch you have? If you are still working on it by the time I am done with uni in a few weeks I can lend a hand testing on different Linux distributions.

Yes, I've created new private branch which I'm working right now to rewrite the app with `Typescript` with a lots of new features and address those issues that are being opened here. 

You can actually help me @sekwah41 testing it with other Linux Distributions because I'm only using Windows and Manjaro. I want to thank you for that.

**Comment by sekwah41** [comment]
> > Are these designs the concept designs to be made or is that the current state of a private branch you have? If you are still working on it by the time I am done with uni in a few weeks I can lend a hand testing on different Linux distributions.
> 
> Yes, I've created new private branch which I'm working right now to rewrite the app with `Typescript` with a lots of new features and address those issues that are being opened here.
> 
> You can actually help me @sekwah41 testing it with other Linux Distributions because I'm only using Windows and Manjaro. I want to thank you for that.

Yea I am currently running Manjaro as my main distro. Though I have virtual machines setup for windows and other distro's for software testing. Seeing as this is open source as apposed to paid software I would recommend using the free version of vmware player or using virtualbox to test any software you make.

Its always helpful to revert machines back to past states ether to test specific hard to reach bugs or seeing if a fresh install of your software on a new machine causes no issues.

**Comment by roldanjrCodeArts9711** [comment]
> virtualbox

Thank you for your advice. But as of now I am budgeting the space of my solid state drive so I can't install operating system as much as I wanted. And thank you if you can help me with that soon.

**Comment by roldanjrCodeArts9711** [comment]
> How one can download and run the code?
> 
> Pls give details about frame work used and how to run the entire code after downloading!

@aahilkabir I provided instructions on how to run the app after downloading inside README.md. 

I hope it would help you. Thanks 👍
