### ISSUE TITLE
Add the ability to disable transition property on timer

### ISSUE THREAD

**Issue by sekwah41** [roldanjrCodeArts9711/productivity-timer#62]
Depending on the system running this application (or possibly this might be tweak-able using parameters) there is an unusually high cpu usage at times (100% of a single thread). I have confirmed that disabling the transition effect on the timer wheel completely negates this.

This is more of a heads up for the current version but also to add into the future version when possible to have the option to toggle or when one of us gets some time to look into ways to better tune electron's performance.

CPU: Ryzen 9 3900x
OS: Manjaro

If anyone else is experiencing this issue please list the CPU and OS you are running and I will look to investigate further. It is not an issue in itself though when running on a laptop it will think an application is needing high performance and drain the battery significantly faster.

**Comment by sekwah41** [comment]
Just a heads up I am looking to getting into writing my future tools and programs with some of the similar stack you are using to build this so I will be looking into these sorts of issues anyway once I get the time :)

**Comment by roldanjrCodeArts9711** [comment]
> Depending on the system running this application (or possibly this might be tweak-able using parameters) there is an unusually high cpu usage at times (100% of a single thread). I have confirmed that disabling the transition effect on the timer wheel completely negates this.
> 
> This is more of a heads up for the current version but also to add into the future version when possible to have the option to toggle or when one of us gets some time to look into ways to better tune electron's performance.
> 
> CPU: Ryzen 9 3900x
> OS: Manjaro
> 
> If anyone else is experiencing this issue please list the CPU and OS you are running and I will look to investigate further. It is not an issue in itself though when running on a laptop it will think an application is needing high performance and drain the battery significantly faster.

@sekwah41 you're right. I quite figured it out that the app seems high in terms of CPU usage and it must not be like that because it's just a timer and need to be as low as possible CPU usage. 

I thought I already solved it in my version 2 that I'm currently working on because it makes the CPU usage twice lesser compared to the version 1 in terms of CPU usage but the good thing is your suggestions really opened my mind for new ideas and I thank you for that. 👍

**Comment by roldanjrCodeArts9711** [comment]
> Just a heads up I am looking to getting into writing my future tools and programs with some of the similar stack you are using to build this so I will be looking into these sorts of issues anyway once I get the time :)

Thanks for your proposal and help. 🥇

**Comment by roldanjrCodeArts9711** [comment]
hey @sekwah41, are you busy this time? 

Is the issue about CPU usage still occurs until now? Please let me know. 
Thank you.

**Comment by sekwah41** [comment]
Yea sorry I am busy until the 14th due to coursework deadlines.

**Comment by roldanjrCodeArts9711** [comment]
> Yea sorry I am busy until the 14th due to coursework deadlines.

I understand because I'm also very busy right now due to project deadline too.

**Comment by roldanjrCodeArts9711** [comment]
@sekwah41 it's been a while. I develop the feature you've requested and already released it.  Please check [Release Notes](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.4.0-beta) I've created for more details of changes I've made.

I hope it would help you. 

![timer-animation](https://user-images.githubusercontent.com/38913069/83366652-1432d200-a3e3-11ea-9737-5e65d0145a8c.gif)

**Comment by sekwah41** [comment]
I will check that in the next few days as I am almost done with my exams but that looks pretty good :)

Loving the look of all the new UI stuff :D

**Comment by roldanjrCodeArts9711** [comment]
> I will check that in the next few days as I am almost done with my exams but that looks pretty good :)
> 
> Loving the look of all the new UI stuff :D


Just take your time. 😁 Thanks

**Comment by sekwah41** [comment]
Works perfectly fine :) I've changed my system a bit though I can see the major performance difference. It goes so low now it basically doesn't register sometimes.

![image](https://user-images.githubusercontent.com/3209834/83520271-53d9e680-a4d5-11ea-8e8e-e4c300e11e09.png)

As for the rest of the stuff id suggest for strict mode add something that make it clear you are in strict mode as I was confused why I couldn't pause the timer. You probably want to hide the priority list if there is no card (atm I use a dedicated list application for general organisation).

Also you need a quick way to delete cards
![image](https://user-images.githubusercontent.com/3209834/83520429-93a0ce00-a4d5-11ea-96bd-1756cb15e0c8.png)

The description part seems to require a double click to be able to type in there for me

**Comment by sekwah41** [comment]
Though for not this issue at least is solved ;)
