### ISSUE TITLE
Disabling sound doesn't disable Narrator for notifications

### ISSUE THREAD

**Issue by Grizzlywolf** [roldanjrCodeArts9711/productivity-timer#64]
Pressing the Sound icon on Timer tab doesn't seem to do anything, both settings play Narrator when notifications show up.

**Comment by roldanjrCodeArts9711** [comment]
@Grizzlywolf thank you for informing me. 
I can confirm it is a bug and I already fixed it in `Version 2.0.4-beta`. 👍
