### ISSUE TITLE
GTK frontend

### ISSUE THREAD

**Issue by digitalethics** [roldanjrCodeArts9711/productivity-timer#65]
Would you consider releasing your app with a GTK-based frontend? I primarily use GNOME and it would blend in better as a native app. Otherwise, I think this app has lots of potential and many functions are well-designed.

**Comment by roldanjrCodeArts9711** [comment]
> Would you consider releasing your app with a GTK-based frontend? I primarily use GNOME and it would blend in better as a native app. Otherwise, I think this app has lots of potential and many functions are well-designed.

@digitalethics I would like too but how? 
I'm very busy right now and have no time to explore.
Do you have any idea?
