### ISSUE TITLE
Timer is wrong

### ISSUE THREAD

**Issue by jedsonmelo** [roldanjrCodeArts9711/productivity-timer#67]
**Describe the bug**
The timer running in background is slower than it shoeld

**To Reproduce**
1. Go to app and start the timer
2. Click on 'X' to close and running in background
3. Start another timer on your browser or smartphone
4. See productivity-timer is slower then another timer.

**Expected behavior**
Timer was correct

**Desktop (please complete the following information):**
 - OS: Deepin 15.5 debain based and Kubuntu 18.04

**Comment by roldanjrCodeArts9711** [comment]
> **Describe the bug**
> The timer running in background is slower than it shoeld
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to app and start the timer
> 2. Click on 'X' to close and running in background
> 3. Start another timer on your browser or smartphone
> 4. See productivity-timer is slower then another timer.
> 
> **Expected behavior**
> Timer was correct
> 
> **Desktop (please complete the following information):**
> 
> * OS: Deepin 15.5 debain based and Kubuntu 18.04

Yes I'd also experience that. Maybe it is because of `setInterval` function delays that I used for count down.

I will try to fix that later after I finish all my project deadlines. 
Thanks for informing me that you had experience that too. It affirms me that it is a bug.

**Comment by roldanjrCodeArts9711** [comment]
@jedsonmelo  it's been a while. I already fixed the bug you've posted and already released it.  Please check [Release Notes](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.4.0-beta) I've created for more details of changes I've made.

I hope it would help you.
