### ISSUE TITLE
Separate toggles for alarm sounds, basic narration and extra narration

### ISSUE THREAD

**Issue by cagils** [roldanjrCodeArts9711/productivity-timer#69]
It would be great for many people if we could disable narration but keep alarm sounds on as it can be too distracting while doing focused work.

For my use case, I only need to turn off all the narration while keeping the basic alarm sounds. But maybe for a better overall user experience something like the following can also be done:

Sounds
- *[ON/OFF]* **ALARM SOUNDS**
   Only rings at the start of each session/break
- *[ON/OFF]* **BASIC NARRATION**
   AFTER the ring of an alarm, only announce the situation by a three-four-word short speech)
- *[ON/OFF]* **EXTRA NARRATION**
   BEFORE a session/break approaches warn the user and all other extra things currently it is doing)

Notifications (On Screen Popups)
- *[ON/OFF]* **BASIC NOTIFICATION**
  Notify the start of each session/break
- *[ON/OFF]* **EXTRA NOTIFICATION**
  Notify before a session/break approaches

Hope this can be added and also thanks for this little great tool !

**Comment by roldanjrCodeArts9711** [comment]
That's great but it is very time consuming to refactor my code and add your request.
In my case I don't have much time right now. Maybe I will put it on app's `ROAD MAP` .

But, if you want as of now I can keep the basic alarm sound and only turn off the narration when you mute the app. Please let me know. Thank you 👍

**Comment by cagils** [comment]
> But, if you want as of now I can keep the basic alarm sound and only turn off the narration when you mute the app. Please let me know. Thank you

Yes, only turning off the narration would be enough on my behalf, thanks!

**Comment by roldanjrCodeArts9711** [comment]
@cagils  I released new version of the app with some parts of the feature you've requested. Please see [Release Notes](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.4.0-beta) I've created for more details of changes I've made.

I hope it would help you. 

![notification-property](https://user-images.githubusercontent.com/38913069/83366797-d71b0f80-a3e3-11ea-8175-35579482f19b.gif)

**Comment by cagils** [comment]
@roldanjrCodeArts9711 That looks amazing! (Sorry I was away for a few days and just seen this. )

This implementation looks clean and fits into the minimalistic design of the app very well. The other features in this release looks also great, thanks.

Have a great day!

> 
> @cagils I released new version of the app with some parts of the feature you've requested. Please see [Release Notes](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.4.0-beta) I've created for more details of changes I've made.
> 
> I hope it would help you.
>

**Comment by roldanjrCodeArts9711** [comment]
Glad to here that @cagils . I think I need to close this. Thank you again.
