### ISSUE TITLE
Bug Report: Javascript error at launch

### ISSUE THREAD

**Issue by Ydeluca** [roldanjrCodeArts9711/productivity-timer#72]
**Describe the bug**
Javascript error at launch

**To Reproduce**

Start the app

**Expected behavior**
App should start without error

**Logs**
`Uncaught Exception:
Error: Image could not be created from /Applications/PRODUCTIVITY TIMER.app/Contents/Resources/app.asar/src/assets/logos/logo-dark.ico
    at createMainWindow (/Applications/PRODUCTIVITY TIMER.app/Contents/Resources/app.asar/build/electron.js:20:11)
    at App.<anonymous> (/Applications/PRODUCTIVITY TIMER.app/Contents/Resources/app.asar/build/electron.js:63:9)
    at App.emit (events.js:223:5)`

**Desktop (please complete the following information):**
 - OS: mac os Catalina
 - Version 10.15.4
- App version : 2.0.7-beta
- Not tested with others app
- It's a fresh install.

**Additional context**

Those app looks amazing, thanks you for your work and I can't wait to test it !

**Comment by roldanjrCodeArts9711** [comment]
I'm really sorry about that @Ydeluca. I haven't tested it on real Mac OS but I will try to figure it out and try to fix it as soon as possible. Thank you for reporting that bug.

**Comment by roldanjrCodeArts9711** [comment]
I just release `v2.0.8-beta`. Please let me know if it fixed the bug on your machine @Ydeluca.
Thank you.

**Comment by Ydeluca** [comment]
thanks you but same error : 
`Uncaught Exception:
Error: Image could not be created from /Applications/PRODUCTIVITY TIMER.app/Contents/Resources/app.asar/src/assets/logos/logo-dark.ico
    at createMainWindow (/Applications/PRODUCTIVITY TIMER.app/Contents/Resources/app.asar/build/electron.js:20:11)
    at App.<anonymous> (/Applications/PRODUCTIVITY TIMER.app/Contents/Resources/app.asar/build/electron.js:63:9)
    at App.emit (events.js:223:5)`

**Comment by roldanjrCodeArts9711** [comment]
Did you update it to the newest version @Ydeluca?

**Comment by Ydeluca** [comment]
Everything works now, thanks you :)

**Comment by roldanjrCodeArts9711** [comment]
> Everything works now, thanks you :)

It's my pleasure. 😊
