### ISSUE TITLE
Bug Report: The app sometimes did not full screen on breaks.

### ISSUE THREAD

**Issue by Hydro8** [roldanjrCodeArts9711/productivity-timer#73]
Hi

On windows 10, the blocking page doesn't appear by itself. I must open the application from statut bar.

Is it normal ?

Thank

**Comment by roldanjrCodeArts9711** [comment]
Can you provide some screenshots of app's current behavior @Hydro8?

**Comment by Hydro8** [comment]
I've found the problem : when you minimize to the windows, the fullscreen doesn't trigger. A way to enable minimzed + fullscreen ?

However, I have another problem. When a timer is in progress, I can't use button under the counter : play / pause, reset....

**Comment by roldanjrCodeArts9711** [comment]
> I've found the problem : when you minimize to the windows, the fullscreen doesn't trigger. A way to enable minimzed + fullscreen ?
> 
> However, I have another problem. When a timer is in progress, I can't use button under the counter : play / pause, reset....

Can you describe the Operating System you used including the specs and graphics of it?
I have a friend too experiencing the same issue with you. 

Regarding with the another problem you stated. Actually it is not a bug, it is the actual behavior of it. 

If you see it has a hand icon which means when the timer start you cannot pause, skip or reset the app. That's the rule when the `Strict Mode` is enabled.

![image](https://user-images.githubusercontent.com/38913069/83320305-c7cb8300-a278-11ea-8682-6880a8e34c1c.png)


![image](https://user-images.githubusercontent.com/38913069/83320274-6efbea80-a278-11ea-92a3-54e988e7f712.png)

**Comment by Hydro8** [comment]
Ok I understand for the buttons, thanks !

For my computer spec : 
- windows 10 pro 1903
- graphic come from my i5-8265u

**Comment by roldanjrCodeArts9711** [comment]
> Ok I understand for the buttons, thanks !
> 
> For my computer spec :
> 
> * windows 10 pro 1903
> * graphic come from my i5-8265u

@Hydro8 as of now it is really hard to figure out the bug because it is really rare to happen. 
Just you and my friend only experiencing that kind of behavior.

As of now please wait for the next released. I will try to find a solution for your concern  as soon as possible. I'm really busy right now with new projects. I hope you will understand. 

Also, I've made a new release of the app. Please check [Release Notes](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.4.0-beta) I've created for more details of changes I've made.

If the future version of the app solves your problem please let me know. Thank you.

**Comment by Hydro8** [comment]
With the last update it seems to work ! Thanks !

Do you plan to add a shorter timer ? I have a 15" laptop and with "always on top" option enable, it's not easy to play with windows.

**Comment by roldanjrCodeArts9711** [comment]
> With the last update it seems to work ! Thanks !
> 
> Do you plan to add a shorter timer ? I have a 15" laptop and with "always on top" option enable, it's not easy to play with windows.

What do mean by that adding shorter timer and not easy to play @Hydro8 ?
I used 15" laptop too.

**Comment by Hydro8** [comment]
How do you handle the timer when on top of all ?

By shorter timer, I mean graphically, reduce the size of timer window and remove menu for example.

**Comment by roldanjrCodeArts9711** [comment]
> How do you handle the timer when on top of all ?
> 
> By shorter timer, I mean graphically, reduce the size of timer window and remove menu for example.

I see your problem but do you prefer to make the app always on top or just hide it when your working? Let me know.

**Comment by Hydro8** [comment]
If I hide it, I don't have fullscreen break :(

**Comment by roldanjrCodeArts9711** [comment]
> If I hide it, I don't have fullscreen break :(

Yeah that's the main problem. I'm sorry for that. 
I suggest you must just disable always on top and just minimize it just what my friend did. 

I will try to figure out soon why it happened on few machines.

**Comment by Hydro8** [comment]
Sadly if something don't interrupt me like your fullscreen, I will continue to work...

So wait and try!

Thanks for your work and your support !

**Comment by roldanjrCodeArts9711** [comment]
> Sadly if something don't interrupt me like your fullscreen, I will continue to work...
> 
> So wait and try!
> 
> Thanks for your work and your support !

@Hydro8 It's really hard for me to solve your problem right now because I'm not experiencing the same issue the same as you. But I will try my best to fix that as soon as possible.

**Comment by roldanjrCodeArts9711** [comment]
@Hydro8 is your problem still occurs with the current version of the app? 
Please let me know. Thank you.

**Comment by Hydro8** [comment]
Hi
Bug still here...:)

**Comment by Hydro8** [comment]
version 2.8.4-beta

**Comment by roldanjrCodeArts9711** [comment]
Hi @Hydro8  . I just released new version of the app. 

Please visit [v2.10.0-beta Release Note](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.10.0-beta).
Also,  let me know if the bug you've encountered fixed by this latest version of the app. Thank you.

**Comment by Hydro8** [comment]
Hi

The new version seems to work !

Thank a lot !
