### ISSUE TITLE
Short Break : NaN minutes

### ISSUE THREAD

**Issue by KiloNovemberDelta** [roldanjrCodeArts9711/productivity-timer#79]
![image](https://user-images.githubusercontent.com/41945728/84013758-a30e9400-a979-11ea-86f4-f8791da34019.png)
Hello,
When I arrive to the Short Break period, I have this NaN : NaN. 
My version is 2.8.4-beta

Hoping this is simple to fix,
Good luck

**Comment by roldanjrCodeArts9711** [comment]
@KiloNovemberDelta I experienced that too after the updates.
I suggest that just restore the default config and try to see if it's working. 👍

**Comment by KiloNovemberDelta** [comment]
I have uninstall and reinstall the software, let the default config as it is. But still doesn't work.. 👎
