### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by roldanjrCodeArts9711** [roldanjrCodeArts9711/productivity-timer#80]
Hi

What was the old way to handle this ?

I like the strict mode to have the fullscreen when it's tile to take a break but I also need to be able to interrupt timer if I'm away for x minutes.

_Originally posted by @Hydro8 in https://github.com/roldanjrCodeArts9711/productivity-timer/issues/66#issuecomment-640484118_

**Comment by roldanjrCodeArts9711** [comment]
@Hydro8 I was thinking to restore the `Full Screen Break` feature of the app separated from `Strict Mode` so that the concerns will become separated. What do you think?

**Comment by Hydro8** [comment]
Yes seems totally fine to me !

That's way we can have full screen break but still can use the buttons :)
