### ISSUE TITLE
Bug Report: Application remains on full screen after break is over

### ISSUE THREAD

**Issue by nagylilla96** [roldanjrCodeArts9711/productivity-timer#85]
**Describe the bug**
After the first break (which will be displayed on full screen), the application doesn't go back to the small window like it was at the first work session, which is really annoying, because you can't put it in the corner of the screen while you're working.

**To Reproduce**
1. I installed it and started running it
2. After the first break was displayed, it looked like the image below
3. Trying to minimize it didn't work

**Expected behavior**
The application should reduce to its small size for work, as it was in the first work session. Closing and restarting the application doesn't help, I haven't tried to kill the task and restart the application yet.

**Screenshots**
![image](https://user-images.githubusercontent.com/20059930/84874771-c4643400-b08d-11ea-99df-fe3fba9422e0.png)

**Desktop:**
 - OS: Windows 10
 - Version 2.8.4 beta

**Additional information**
Could you please rename `Stay Focus` to `Stay Focused` on this screen, please?
Also, I don't know the exact steps to reproduce this, it happened to me the first time I ran the program. In the next few days, I will come back with more details whether it keeps on reproducing or not.

**Comment by roldanjrCodeArts9711** [comment]
@nagylilla96 It didn't happened to me but thanks for informing me about that. 
I'm working with the new features of the app right now and trying to fix some issues.
I will try to solve it as soon as possible. Thank you for your patience.

**Comment by roldanjrCodeArts9711** [comment]
I suggest, as of now just try quitting the app and start it again.

**Comment by nagylilla96** [comment]
Thank you :) I will announce you if it reproduces when I restart it

**Comment by nagylilla96** [comment]
It didn't reproduce, but this time, during the break it didn't cover the full screen. This doesn't bother me, maybe you could have a feature where you could enable/disable that, but bringing the application to the top (in front of all other applications) would be nice instead :)

**Comment by roldanjrCodeArts9711** [comment]
I will inform you when I release new version of the app. Thank you for informing me about the bug.

**Comment by nagylilla96** [comment]
Thank you for the quick response! Have a nice day 😄

**Comment by roldanjrCodeArts9711** [comment]
Hi @nagylilla96 . I just released new version of the app. 

Please visit [v2.10.0-beta Release Note](https://github.com/roldanjrCodeArts9711/productivity-timer/releases/tag/v2.10.0-beta).
Also,  let me know if the bug you've encountered fixed by this latest version of the app. Thank you :heart: .

**Comment by roldanjrCodeArts9711** [comment]
@nagylilla96  is there any updates with this issue?

**Comment by roldanjrCodeArts9711** [comment]
I think I need to close it. Just open the issue again if the bug still persist.
