### ISSUE TITLE
Minimize to "tray" or title bar on macOS

### ISSUE THREAD

**Issue by moltar** [roldanjrCodeArts9711/productivity-timer#87]
**Is your feature request related to a problem? Please describe.**

The app takes up space in the dock.

**Describe the solution you'd like**

I'd like to be able to minimize the app to the title bar, so it does not take up any space in the dock.

There seems to be already a title icon, but the only option it has is "quit". Also the icon is larger than the space.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A
<img width="155" alt="image" src="https://user-images.githubusercontent.com/491247/85198771-69dd0900-b315-11ea-989b-c27cc050cefa.png">

**Comment by roldanjrCodeArts9711** [comment]
I'm sorry about that. I have only Windows and Linux to test. 

I will try to resize the tray icon for Mac.

But regarding with the context menu in tray icon. 
I removed `Show` and `Hide` option because I find it useless. 

It might be a good idea if only shows the tray icon when the app is being hide. 

Let me know your thoughts.

**Comment by roldanjrCodeArts9711** [comment]
@moltar if it is okey for you. Since you are using Mac OS. 

I would like to ask a favor to test the code with your machine and create a pull request with the solutions you've made. It is really hard for me to fix some of the bugs specially with Mac OS because I can't test it.

**Comment by moltar** [comment]
The icon seems to be fixed in the latest release.

<img width="114" alt="image" src="https://user-images.githubusercontent.com/491247/85218123-75860980-b3c1-11ea-9bb9-7c4ceec184e4.png">

But the release notes mention minimize to tray on macOS, but I am not seeing any settings for that on the Settings screen. How is it supposed to work?

Thanks.

**Comment by roldanjrCodeArts9711** [comment]
Yes you're right. It is not actually `Minimize to Tray`, the correct term is `Close to Tray`. 

Minimize behavior still the same as normal window but clicking the close button will only hide the app and create system tray icon with context menu.

You can only quit the app using the `Quit` option from tray.
