### ISSUE TITLE
Timer on systray icon

### ISSUE THREAD

**Issue by Hydro8** [roldanjrCodeArts9711/productivity-timer#93]
Hi

Two things :

- when I reduce timer to tray, it's hidding by default. So I move it and drop it next to hour. But every time I show then reduce timer window, the icon is hiding in tray. Something can be done about this ?

- Is it possible to think of adding a little timer on tray icon to display remaining minutes then seconds ?

Thank  for your work, very awesome timeer !

**Comment by roldanjrCodeArts9711** [comment]
> * when I reduce timer to tray, it's hidding by default. So I move it and drop it next to hour. But every time I show then reduce timer window, the icon is hiding in tray. Something can be done about this ?

![image](https://user-images.githubusercontent.com/38913069/86215754-8d267480-bbaf-11ea-800d-f2e1c6a97043.png)

When you enabled `Minimize to Tray` feature. Clicking the minimize button will not minimize the app. Instead, it will be hidden and send to tray. It you want to preserve the native functionality of minimize button, just disable it. 

> * Is it possible to think of adding a little timer on tray icon to display remaining minutes then seconds ?

I think it is not possible to do so but I had a plan to do some tray progress but not exactly what you wanted.

**Comment by Hydro8** [comment]
- I mean keep the systray icon on visible part of systray.

![n2FrrnI9uP](https://user-images.githubusercontent.com/5537697/86234111-bd154e00-bb96-11ea-8dba-977b61a4765d.gif)

- ok so my first question isn't relevant anymore if you find another way to see time remaining.

**Comment by roldanjrCodeArts9711** [comment]
That's actually the new behavior I developed. On my Linux and some of the Mac users they don't want duplicate app icon on their taskbar. So I decided not to create System Tray Icon on initial load. Only create tray when the user will minimize or close the app.

**Comment by roldanjrCodeArts9711** [comment]
Let me know your thoughts too if you don't want that kind of behavior.

**Comment by Hydro8** [comment]
It's not a big deal if you'll show remaining time with another method.

I was thinking about this if the timer was placed on the systray icon.
