### ISSUE TITLE
Bug Report: Counter continues where it is left off after computer sleeps and wakes up

### ISSUE THREAD

**Issue by snnsnn** [roldanjrCodeArts9711/productivity-timer#95]
**Describe the bug**
This may not be a bug but an intentional design. 

I usually put my computer to sleep mode during long break, when the computer wakes up productivity timer's counter continues exactly where it is left off. So, I had to wait for another long break. Now I am keeping my computer on during long breaks just to get the counter on, which is a bit wasteful.

I assume it is using internal counter and with setInterval or setTimeout, but counter should respect the actual time especially for locks and unlocks.

Please can you fix it. Thank you for the app, it is really useful.

**Comment by roldanjrCodeArts9711** [comment]
**Desktop (please complete the following):**
 - OS: [e.g. Windows]
 - App Version [e.g. 22]

It is very helpful if you will fill this up. Thank you.
