### ISSUE TITLE
Remaining time mode

### ISSUE THREAD

**Issue by Hydro8** [roldanjrCodeArts9711/productivity-timer#96]
Hi

Is it possible to add an option (another one....) to switch between circle and number for remaining time ?

It's a great job for the circle, very useful, but most time I want to know how much time remains until next break and it's not very easy to see that with the circle.

Very good update through, didn't have the problem with hidding systray icon anymore !

**Comment by roldanjrCodeArts9711** [comment]
I can only show remaining time when hovering the tray icon.

**Comment by Hydro8** [comment]
Too bad that you can display it all the time.

**Comment by roldanjrCodeArts9711** [comment]
>Is it possible to add an option (another one....) to switch between circle and number for remaining time ?

I think It is not a good idea to display remaining time that will replace the tray icon with progress indicator. I'm sorry.

I suggest, just use the shortcut key `Ctrl / Cmd + Shift + S` to check the remaining time. And hide it if you want using `Ctrl / Cmd + Shift + H`.

**Comment by roldanjrCodeArts9711** [comment]
I might develop feature that will show remaining time without restoring the app soon.
As of now I need to focus on other things rather than consuming all my free time building new features of the app.
I hope you will understand.

**Comment by Hydro8** [comment]
Yes I understand that must develope other points ! 

Thank for considering this !

**Comment by roldanjrCodeArts9711** [comment]
I'm really sorry @Hydro8 . I tried to make it but it seems impossible to do.

I advice just change the `Notification Property` set to `Extra`.
It will inform you when `30 seconds left remaining work time` and when `60 seconds left for your break`.

**Comment by Hydro8** [comment]
Thank a lot to have considering this !

And thank for the extra tip.
